import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Love Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="relative flex min-h-dvh justify-center bg-gradient-to-br from-pink-200 to-rose-300 p-2 overflow-hidden">
          <div className="absolute w-full h-full flex items-center justify-center pointer-events-none">
            <div className="relative w-80 h-80 animate-pulse bg-none">
              <div className="absolute w-80 h-80 top-0 left-20 bg-pink-400 rounded-full blur-2xl opacity-50" />
              <div className="absolute w-80 h-80 top-0 right-10 bg-rose-400 rounded-full blur-2xl opacity-50" />
            </div>
          </div>

          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
